#!/bin/sh
DEFAULT="innotek GmbH"
VENDORFIELD="Hardware Vendor:"

HVENDOR=$(hostnamectl | sed -nE "/$VENDORFIELD/s/.*: *//p")
HCURRENT=$(hostnamectl hostname)

case "$HVENDOR/$HCURRENT/$#" in
	*/*/1) hostnamectl hostname "$1"; kill -HUP $PPID
		;;
	localhost/*|"$DEFAULT"/*|"$HVENDOR/$HVENDOR"/*) # Do not touch
		;;
	*/localhost/0) hostnamectl hostname "$HVENDOR"
		;;
esac
	
